services:
  - type: worker
    env: node
    name: github-stars-to-slack
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/index.js"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
      - key: GITHUB_REPOSITORY
        sync: false